'use strict';

var CHOCOLATE_DUKE_REV_X = 1;
var CHOCOLATE_DUKE_REV_DOT_Y = 0;

var UNKNOWN_GRP = 0;
var SHAREWARE_GRP13 = 1;
var REGULAR_GRP13D = 2;
var ATOMIC_GRP14_15 = 3;
var DUKEITOUTINDC_GRP = 4;

var mymembuf;

function Player() {
}

var MODE_MENU = 1;
var MODE_DEMO = 2;
var MODE_GAME = 4;
var MODE_EOL = 8;
var MODE_TYPE = 16;
var MODE_RESTART = 32;
var MODE_SENDTOWHOM = 64;
var MODE_END = 128;

var MAXANIMWALLS = 512;
var MAXINTERPOLATIONS = 2048;
var NUMOFFIRSTTIMEACTIVE = 192;

var MAXCYCLERS = 256;
var MAXSCRIPTSIZE = 20460;
var MAXANIMATES = 64;